version: '3.8'

services:
  strapi:
    build: ./
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: sqlite
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      S3_BUCKET: strapi-local-bucket
      S3_ENDPOINT: http://localstack:4566
    depends_on:
      - localstack
    volumes:
      - ./strapi:/srv/app
    command: ["sh", "-c", "yarn install && yarn develop"]

  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      SERVICES: s3,dynamodb
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
