name: Terraform Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v3
      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y terraform
      - name: Terraform Init
        run: terraform -chdir=infra init
      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve
