name: Docker Build and Push
on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t mystrapi:latest .
      - name: Push Docker image
        run: |
          docker tag mystrapi:latest ${{ secrets.DOCKER_USERNAME }}/mystrapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mystrapi:latest
